--!strict
-- uro ;)

-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
-- This has been deprecated in faver of server sound playing.
-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


-- Plays the keyboard press sound when a key is pressed.

-- local event: RemoteEvent = game:GetService("ReplicatedStorage").PlaySound
-- 
-- local SoundUrl: string = "rbxassetid://18998603679" -- Sound URL played
-- 
-- local function playSound()
-- 	local newSound = Instance.new("Sound")
--   newSound.SoundId = SoundUrl
-- 	newSound.Parent = script.Parent
-- 	newSound:Play()
--   newSound.Volume = 2
-- 	
-- 	newSound.Ended:Connect(function()
-- 		newSound:Destroy()
-- 	end)
-- end
-- 
-- event.OnClientEvent:Connect(playSound)

